/**
 * Assignment status constants, kept OUT of db.types.ts because that file is
 * regenerated by `supabase gen types typescript` and would lose them.
 * These mirror public.assignments_status_guard in
 * supabase/migrations/0003_functions.sql — change both together.
 */
import type { AssignmentStatus } from "@/lib/db.types";

export type { AssignmentStatus };

/** Every status, in machine order. Useful for filters and tabs. */
export const ASSIGNMENT_STATUSES = [
  'assigned',
  'in_progress',
  'submitted',
  'approved',
  'redo',
] as const satisfies readonly AssignmentStatus[]

/**
 * Transitions the database accepts (public.assignments_status_guard).
 * The UI must not offer anything outside this map.
 */
export const ASSIGNMENT_TRANSITIONS: Record<AssignmentStatus, AssignmentStatus[]> = {
  assigned: ['in_progress', 'submitted'],
  in_progress: ['submitted'],
  submitted: ['approved', 'redo'],
  approved: ['redo', 'in_progress'], // parent-only correction
  redo: ['in_progress'],
}

/** Transitions only a parent (or a helper with review rights) may perform. */
export const REVIEWER_ONLY_TARGETS = ['approved', 'redo'] as const

export const STORAGE_BUCKET_EVIDENCE = 'evidence' as const
